# Generated by Django 4.1.3 on 2022-11-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название чата'),
        ),
    ]
