# Generated by Django 4.1.3 on 2022-11-14 20:41

from django.conf import settings
import django.contrib.sessions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sessions.session')),
                ('name_device', models.CharField(max_length=25, verbose_name='Название устройства')),
                ('latest_activity', models.DateTimeField(auto_now_add=True, verbose_name='Последняя активность')),
                ('geolocation', models.CharField(max_length=25, verbose_name='Местоположение устройства')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес устройства')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна сессия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'abstract': False,
            },
            bases=('sessions.session',),
            managers=[
                ('objects', django.contrib.sessions.models.SessionManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='users_session',
            name='user',
        ),
        migrations.DeleteModel(
            name='MySession',
        ),
        migrations.DeleteModel(
            name='Users_Session',
        ),
    ]
