# Generated by Django 4.1.3 on 2022-11-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersession_remove_users_session_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
