# Generated by Django 4.1.3 on 2022-11-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_messages', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='kind',
            field=models.CharField(max_length=30, verbose_name='Вид реакции'),
        ),
    ]
