# Generated by Django 4.1.3 on 2022-11-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats_messages', '0003_alter_reaction_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreaction',
            options={'verbose_name': 'Реакция пользователей', 'verbose_name_plural': 'Реакции пользователей'},
        ),
    ]
